// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SUT23_Labb3_API.Data;

#nullable disable

namespace SUT23_Labb3_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240425205046_changed views")]
    partial class changedviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SUT23_Labb3_API.Models.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestId"));

                    b.Property<string>("InterestDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterestName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterestId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestId = 1,
                            InterestDescription = "Programming in C#",
                            InterestName = "Programmering"
                        },
                        new
                        {
                            InterestId = 2,
                            InterestDescription = "Playing golf",
                            InterestName = "Golf"
                        },
                        new
                        {
                            InterestId = 3,
                            InterestDescription = "How they work",
                            InterestName = "Computers"
                        },
                        new
                        {
                            InterestId = 4,
                            InterestDescription = "World of Warcraft",
                            InterestName = "Gaming"
                        },
                        new
                        {
                            InterestId = 5,
                            InterestDescription = "Playing instrument",
                            InterestName = "Music"
                        });
                });

            modelBuilder.Entity("SUT23_Labb3_API.Models.InterestPersonLink", b =>
                {
                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("LinkId")
                        .HasColumnType("int");

                    b.HasKey("InterestId", "PersonId", "LinkId");

                    b.HasIndex("LinkId");

                    b.HasIndex("PersonId");

                    b.ToTable("InterestPersonLinks");

                    b.HasData(
                        new
                        {
                            InterestId = 1,
                            PersonId = 2,
                            LinkId = 1
                        },
                        new
                        {
                            InterestId = 1,
                            PersonId = 2,
                            LinkId = 2
                        },
                        new
                        {
                            InterestId = 3,
                            PersonId = 3,
                            LinkId = 3
                        },
                        new
                        {
                            InterestId = 2,
                            PersonId = 1,
                            LinkId = 3
                        },
                        new
                        {
                            InterestId = 2,
                            PersonId = 1,
                            LinkId = 4
                        },
                        new
                        {
                            InterestId = 4,
                            PersonId = 3,
                            LinkId = 3
                        },
                        new
                        {
                            InterestId = 1,
                            PersonId = 3,
                            LinkId = 3
                        },
                        new
                        {
                            InterestId = 4,
                            PersonId = 1,
                            LinkId = 3
                        },
                        new
                        {
                            InterestId = 5,
                            PersonId = 2,
                            LinkId = 5
                        });
                });

            modelBuilder.Entity("SUT23_Labb3_API.Models.Link", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkId"));

                    b.Property<string>("LinkName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LinkId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            LinkId = 1,
                            LinkName = "https://sv.wikipedia.org/wiki/Programmering"
                        },
                        new
                        {
                            LinkId = 2,
                            LinkName = "https://sv.wikipedia.org/wiki/C"
                        },
                        new
                        {
                            LinkId = 3,
                            LinkName = "https://sv.wikipedia.org/wiki/Golf"
                        },
                        new
                        {
                            LinkId = 4,
                            LinkName = "https://sv.wikipedia.org/wiki/Tiger_Woods"
                        },
                        new
                        {
                            LinkId = 5,
                            LinkName = "https://sv.wikipedia.org/wiki/Musik"
                        });
                });

            modelBuilder.Entity("SUT23_Labb3_API.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("PersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            PersonName = "Peter",
                            PhoneNr = "1234567890"
                        },
                        new
                        {
                            PersonId = 2,
                            PersonName = "Johan",
                            PhoneNr = "6758493201"
                        },
                        new
                        {
                            PersonId = 3,
                            PersonName = "Sara",
                            PhoneNr = "0987654321"
                        });
                });

            modelBuilder.Entity("SUT23_Labb3_API.Models.InterestPersonLink", b =>
                {
                    b.HasOne("SUT23_Labb3_API.Models.Interest", "Interests")
                        .WithMany("InterestPersonLinks")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SUT23_Labb3_API.Models.Link", "Links")
                        .WithMany("InterestPersonLinks")
                        .HasForeignKey("LinkId");

                    b.HasOne("SUT23_Labb3_API.Models.Person", "Persons")
                        .WithMany("InterestPersonLinks")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interests");

                    b.Navigation("Links");

                    b.Navigation("Persons");
                });

            modelBuilder.Entity("SUT23_Labb3_API.Models.Interest", b =>
                {
                    b.Navigation("InterestPersonLinks");
                });

            modelBuilder.Entity("SUT23_Labb3_API.Models.Link", b =>
                {
                    b.Navigation("InterestPersonLinks");
                });

            modelBuilder.Entity("SUT23_Labb3_API.Models.Person", b =>
                {
                    b.Navigation("InterestPersonLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
